[package]
name = "tasky-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.26"
colored = "3.0.0"
dirs = "5.0.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
