name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build project
        run: cargo build --release

      - name: Archive build artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czf tasky-rs-linux-x64.tar.gz -C target/release tasky-rs
          sha256sum tasky-rs-linux-x64.tar.gz > tasky-rs-linux-x64.tar.gz.sha256sum

      - name: Archive build artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path target/release/tasky-rs.exe -DestinationPath tasky-rs-windows-x64.zip
          Get-FileHash -Algorithm SHA256 tasky-rs-windows-x64.zip | ForEach-Object { $_.Hash } > tasky-rs-windows-x64.zip.sha256sum

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            tasky-rs-linux-x64.tar.gz
            tasky-rs-linux-x64.tar.gz.sha256sum
            tasky-rs-windows-x64.zip
            tasky-rs-windows-x64.zip.sha256sum

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-artifacts
          path: ./artifacts/linux
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-artifacts
          path: ./artifacts/windows

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./artifacts/linux/tasky-rs-linux-x64.tar.gz
            ./artifacts/linux/tasky-rs-linux-x64.tar.gz.sha256sum
            ./artifacts/windows/tasky-rs-windows-x64.zip
            ./artifacts/windows/tasky-rs-windows-x64.zip.sha256sum
          token: ${{ secrets.TASKY_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            Release notes for ${{ github.ref }}